global:
  resolve_timeout: 5m
receivers:
- email_configs:
  - auth_identity: noreply@spectrocloud.com
    auth_password: abcd
    auth_username: noreply@spectrocloud.com
    from: noreply@spectrocloud.com
    send_resolved: true
    smarthost: smtp.gmail.com:587
    to: mark@spectrocloud.com
  name: prom-alert
route:
  group_by:
  - job
  group_interval: 5m
  group_wait: 30s
  receiver: prom-alert
  repeat_interval: 4h
  routes:
  - match:
      alertname: Watchdog
    receiver: prom-alert