apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_alert: "1"
  name: crypto-alert
  namespace: monitoring
data:
  crypto-alert.yaml: |
    apiVersion: 1
    groups:
      - orgId: 1
        name: 'New Alert'
        folder: Crypto Alerts
        interval: 60s
        rules:
          - uid: my_id_1
            title: crypto_alert
            condition: A
            data:
              - refId: A
                datasourceUid: '-100'
                model:
                  conditions:
                    - evaluator:
                        params:
                          - 3
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                          - A
                      reducer:
                        type: last
                      type: query
                  datasource:
                    type: __expr__
                    uid: '-100'
                  expression: 1==0
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: A
                  type: math
            dashboardUid: my_dashboard
            panelId: 123
            noDataState: Alerting
            for: 60s
            annotations:
              some_key: some_value
            labels:
              team: sre_team_1