nameOverride: prometheus
fullnameOverride: prometheus
commonLabels:
  cluster: infra-tools
  stage: prod
  region: us-east-1

grafana:
  enabled: false
alertmanager:
  enabled: false

prometheusOperator:
  serviceAccount:
    create: false
    name: thanos-role
  kubeletService:
    enabled: true
  resources:
    requests:
      cpu: 500m
      memory: 100Mi
    limits:
      cpu: 700m
      memory: 200Mi

prometheus: 
  serviceAccount:
    create: false
    name: thanos-role
  prometheusSpec:
    externalLabels:
      cluster: infra-tools
      region: us-east-1
    scrapeInterval: "1m"
    scrapeTimeout: "60s"
    evaluationInterval: "1m"
    retention: 7d
    resources:
      requests:
        cpu: 200m
        memory: 1000Mi
      limits:
        cpu: 2500m
        memory: 20000Mi
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: prometheus
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 30Gi
    thanos:
      objectStorageConfig:
        name: thanos-objstore-config
        key: thanos.yaml
  thanosServiceExternal:
    labels:
      cluster: infra-tools
      region: us-east-1
    enabled: false
  thanosIngress:
    enabled: true
    labels:
      cluster: infra-tools
      region: us-east-1
    pathType: Prefix
    path: /
    hosts: 
    - thanos-infra-tools.aws.aurotfp.com
    annotations:
      kubernetes.io/ingress.class: alb
      external-dns/zone: private
      external-dns.alpha.kubernetes.io/hostname: thanos-infra-tools.aws.aurotfp.com
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/subnets: subnet-05d4d4c4e1892a87f, subnet-0cddf53b1f11420f6
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
      alb.ingress.kubernetes.io/backend-protocol-version: GRPC
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:770688751007:certificate/a04e263f-8c9d-4e1f-a3ca-8bf79fbcf5e6
  #   allowed_domains: 

kubeStateMetrics:
  enabled: true
nodeExporter:
  enabled: true