apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-tls
  namespace: monitoring
spec:
  secretName: monitoring-tls
  issuerRef:
    name: cert-manager-selfsigned
    kind: ClusterIssuer
  dnsNames:
  - kube-prometheus-stack-thanos-discovery.monitoring.svc.cluster.local
  - thanos-storegateway.monitoring.svc.cluster.local
  - thanos-ruler.monitoring.svc.cluster.local